services:
  - type: web
    name: klh-peer-learning-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://klhuser:KlhPeerLearning123!@perplexedui.j7czeem.mongodb.net/klh-peer-learning?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: klh_jwt_secret_2024_make_this_long_and_random_123
      - key: JWT_EXPIRES_IN
        value: 90d
      - key: GEMINI_API_KEY
        value: your_gemini_api_key_here
      - key: FRONTEND_URL
        value: https://klh-peer-learning-frontend.onrender.com

  - type: web
    name: klh-peer-learning-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://klh-peer-learning-backend.onrender.com
